# GitHub Metrics for @krishrathi1
name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}]  # Runs daily at 16:00 UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🦑 Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_achievements: yes
          plugin_topics: yes
